granal1/scrum-L

composer.json
composer.lock

composer require symfony/polyfill-uuid

composer require symfony/polyfill-uuid

---

database/migrations/2022_12_20_130109_create_roles_table.php
database/seeders/DatabaseSeeder.php
database/seeders/Roles/RoleSeeder.php

Добавлена таблица ролей и их заполнение по дефолту

Goncharenko

---

app/Http/Controllers/Tasks/TaskController.php
resources/views/tasks/create.blade.php
routes/web.php

Исправил путь /

---

app/Http/Controllers/Users/UserController.php
resources/views/tasks/index.blade.php
resources/views/users/create.blade.php
routes/web.php

Подключил новую страницу карточки сотрудника

Подключил новую страницу карточки сотрудника

---

composer.json

Добавил все команды для запуска в скрипт композера

Добавил все команды для запуска в скрипт композера

---

app/Http/Controllers/Users/UserController.php
resources/views/users/edit.blade.php
resources/views/users/show.blade.php

Добавил просмотр одного пользователя, удаление пользователя

Добавил просмотр одного пользователя, удаление пользователя

---

app/Http/Controllers/Users/UserController.php
app/Http/Requests/Users/StoreUserFormRequest.php
app/Http/Requests/Users/UpdateUserFormRequest.php
app/Models/User.php
database/migrations/2014_10_12_000000_create_users_table.php
resources/views/message.blade.php
resources/views/users/create.blade.php
resources/views/users/edit.blade.php
resources/views/users/show.blade.php

Добавил редактирование пользователя и создание, первая рабочая версия

Добавил редактирование пользователя и создание, первая рабочая версия

---

app/Http/Controllers/Users/UserController.php
app/Http/Requests/Users/StoreUserFormRequest.php
app/Http/Requests/Users/UpdateUserFormRequest.php
app/Models/User.php
resources/views/users/create.blade.php
resources/views/users/edit.blade.php
resources/views/users/show.blade.php

Добавил возможность выбирать одного подчиненного и редактировать его

Добавил возможность выбирать одного подчиненного и редактировать его

---

app/Http/Controllers/Admin/AdminController.php
resources/views/admin/index.blade.php
resources/views/menu.blade.php
routes/web.php

Добавил для админки главную, контроллер, роуты

Добавил для админки главную, контроллер, роуты

---

app/Http/Controllers/Documents/DocumentController.php
app/Http/Controllers/Tasks/TaskController.php
app/Http/Requests/Documents/StoreDocumentFormRequest.php
app/Http/Requests/Tasks/StoreTaskFormRequest.php
app/Http/Requests/Tasks/UpdateTaskFormRequest.php
app/Models/Tasks/Task.php
app/Models/Tasks/TaskFile.php
resources/views/tasks/create.blade.php
resources/views/tasks/edit.blade.php
resources/views/tasks/show.blade.php

Добавил прикрепление уже загруженных документов к задаче

Добавил прикрепление уже загруженных документов к задаче

---

app/Http/Controllers/Users/UserController.php
app/Http/Filters/AbstractFilter.php
app/Http/Filters/FilterInterface.php
app/Http/Filters/Users/UserFilter.php
app/Http/Requests/Users/UserFilterRequest.php
app/Models/Traits/Filterable.php
app/Models/User.php
resources/views/users/index.blade.php

Добавил фильтр по имени и почте для сотрудников

Добавил фильтр по имени и почте для сотрудников

---

app/Http/Requests/Users/UpdateUserFormRequest.php
database/migrations/2014_10_12_000000_create_users_table.php
resources/views/users/edit.blade.php

Подправил проверку и вывод даты рождения сотрудника

Подправил проверку и вывод даты рождения сотрудника

---

resources/views/users/show.blade.php

Подправил вывод даты рождения сотрудника

Подправил вывод даты рождения сотрудника

---

app/Http/Controllers/Tasks/TaskController.php
app/Http/Filters/Tasks/TaskHistoryFilter.php
app/Http/Filters/Tasks/TaskPriorityFilter.php
app/Http/Requests/Tasks/TaskFilterRequest.php
app/Models/Tasks/Task.php
app/Models/Tasks/TaskHistory.php
app/Models/Tasks/TaskPriority.php
resources/views/tasks/index.blade.php

- Убрать uuid, Создана.
- Добавить приоритет.
- Порядок: Приоритет, Описание, Ответственный, Выполнить до, Выполнено %
- Сортировка - по дате выполнения.

В списке задач

---

resources/views/tasks/show.blade.php

- Убрать поле uuid, кнопку Все задачи (могу объяснить причину)
- Приложение сделать в строке описание задачи, второй колонкой

Карточка задачи (просмотр):

---

resources/views/tasks/edit.blade.php

- убрать кнопки Все задачи, Удалить (могу объяснить причину) Убрать кнопку, удаляющую приложение.
-Порядок кнопок: Назад, Сохранить, Создать подзадачу

Карточка задачи (редактирование):

---

resources/views/documents/show.blade.php
resources/views/tasks/progress.blade.php

Убрать uuid, кнопку Все документы.

Страница "Карточка документа"

---

resources/views/documents/edit.blade.php

- убрать кнопку Все документы. Порядок кнопок: Назад, Сохранить, Удалить.
Кнопка Назад должна возвращать на Карточку документа, даже если редактировалось несколько раз

Карточка Редактирование документа

---

public/assets/documents/create.js
resources/views/documents/create.blade.php

В поле описание подставлять описание документа "по умолчанию" как назывался файл, чтобы не надо было изменять, если название устраивает

Страница загрузки документа:

---

database/seeders/Tasks/TaskPrioritySeeder.php
resources/views/tasks/create-subtask.blade.php
resources/views/tasks/create.blade.php

Виды приоритетов предлагается:
- высокий
- выше среднего
- средний
- ниже среднего
- низкий

Приоритет по дефолту должен предлагаться "средний".

---

app/Http/Controllers/Profile/ProfileController.php
app/Http/Controllers/Users/UserController.php
app/Http/Requests/Profile/UpdateProfileFormRequest.php
resources/views/profile/edit.blade.php
resources/views/profile/show.blade.php
resources/views/users/edit.blade.php

Не должно быть выбора подчиненного, он должен формироваться по принципу подчиненности, то есть составляться из тех сотрудников, у которых "этот сотрудник" заявлен начальником. Можно нумерованным списком

Карточка редактирование профиля.

---

resources/views/documents/index.blade.php
resources/views/tasks/edit.blade.php
resources/views/tasks/index.blade.php

Баг - task/edit строка 26 ? не показывает название прикреплённого документа
Баг - task/index поле фильтра по описанию, после поиска если начать новый добавляет пробел в конце предыдущего запроса
Баг - documents/index поле фильтра по описанию, после поиска если начать новый добавляет пробел в конце предыдущего запроса

Исправлены баги:
